name: frc_8033_scouting_shared
description: A starting point for Dart libraries or applications.
version: 4.3.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.18.5 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
dependencies:
  http: ^0.13.5
  flutter:
    sdk: flutter
  lzstring: ^2.0.0+2
